version: "2"

services:
  rngetf:
    build: rngetf
    ports:
    - "8000:80"

  rngtech:
    build: rngtech
    ports:
    - "8001:80"

  rngcrypto:
    build: rngcrypto
    ports:
    - "8002:80"

  redis:
    image: redis

  broker:
    build: broker
