apiVersion: apps/v1
kind: Deployment
metadata:
  name: rngcrypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rngcrypto
  template:
    metadata:
      labels:
        app: rngcrypto
    spec:
      containers:
      - name: rngcrypto
        image:  DOCKER_REGISTRY/rng:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80

