apiVersion: apps/v1
kind: Deployment
metadata:
  name: rngetf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rngetf
  template:
    metadata:
      labels:
        app: rngetf
    spec:
      containers:
      - name: rngetf
        image:  DOCKER_REGISTRY/rng:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
