
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rngtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rngtech
  template:
    metadata:
      labels:
        app: rngtech
    spec:
      containers:
      - name: rngtech
        image:  DOCKER_REGISTRY/rngtech:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
