apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  selector:
    app: webui

---

apiVersion: v1 
kind: Service 
metadata:  
  name: mysql 
spec:  
  ports:    
    - port: 6379      
      protocol: TCP      
      targetPort: 6379  
  selector:    
      app: mysql
 
---

apiVersion: v1 
kind: Service 
metadata:  
  name: rngcrypto
spec:  
  ports:    
    - port: 80      
      protocol: TCP      
      targetPort: 80  
  selector:    
      app: rngcrypto
      
---


apiVersion: v1 
kind: Service 
metadata:  
  name: rngtech
spec:  
  ports:    
    - port: 80      
      protocol: TCP      
      targetPort: 80  
  selector:    
      app: rngtech
      
---


apiVersion: v1 
kind: Service 
metadata:  
  name: rngetf 
spec:  
  ports:    
    - port: 80      
      protocol: TCP      
      targetPort: 80  
  selector:    
      app: rngetf
